spring.application.name=AIFN


spring.datasource.url=jdbc:mysql://localhost:3306/ml_prediction_system
spring.datasource.username=root
spring.datasource.password=Aryan@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080